# Generated by Django 5.2.6 on 2025-09-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='resident',
            name='is_principal',
            field=models.BooleanField(default=False, help_text='Is this the principal resident (owner or main tenant) of the unit?'),
        ),
    ]
